<<<<<<< HEAD
import "../index.css";
import { LangProvider } from "../hooks/useLang";

export const metadata = {
  title: "Apex — Construction & Contracting",
  description: "Apex construction and contracting services.",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 774b91ad77f23b5422d85b8346a9d9137d4c865b
};

export default function RootLayout({ children }) {
  return (
<<<<<<< HEAD
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <body className="min-h-full flex flex-col font-sans">
        <LangProvider>{children}</LangProvider>
      </body>
=======
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> 774b91ad77f23b5422d85b8346a9d9137d4c865b
    </html>
  );
}
